# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# We have to ignore lazypdf because we have to build it manually due to the C
# library download and build.

ignored = ["github.com/Nitro/lazypdf"]

[[constraint]]
  branch = "master"
  name = "github.com/Nitro/sidecar"

[[constraint]]
  branch = "master"
  name = "github.com/Nitro/memberlist"

[[constraint]]
  branch = "master"
  name = "github.com/Nitro/ringman"

[[constraint]]
  branch = "master"
  name = "github.com/Nitro/filecache"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "0.10.0-16-gcd7d1bb"

[[constraint]]
  branch = "v1"
  name = "github.com/bsm/redeo"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0-3-g8bf4bbf"

[[constraint]]
  name = "github.com/relistan/rubberneck"
  version = "1.0.1"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = ">=1.6.2, <=17.0.0-g3bd662e"

[[constraint]]
  name = "github.com/yvasiyarov/gorelic"
  revision = "ae09aa139a2b7f638e2412baceaceebd41eff115"
